password = [
    48,
    48,
    116,
    104,
    86,
    67,
    69,
    110,
    114,
    52,
    67,
    73,
    70,
    80,
    71,
    103,
    108,
    107,
    56,
    112,
    65,
    66,
    48,
    89,
    89,
    108,
    48,
    66,
    119,
    72,
    53,
    84,
    118,
    117,
    90,
    83,
    78,
    53,
    49,
    74,
    51,
    47,
    85,
    79,
    50,
    69,
    78,
    101,
    100,
    100,
    97,
    83,
    106,
    65,
    89,
    121,
    73,
    85,
    55,
    65,
    72,
    55,
    102,
    106,
    74,
    101,
]
size = [
    0,
    0,
    0,
    0,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'original'
scroll_style = 'scrollauto'
image_quality = 'balanced'
custom_image_quality = [50]
show_remote_cursor = false
lock_after_session_end = false
terminal-persistent = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 1
disable_audio = false
disable_clipboard = false
enable-file-copy-paste = true
show_quality_monitor = false
follow_remote_cursor = false
follow_remote_window = false
keyboard_mode = 'map'
view_only = false
sync-init-clipboard = false
trackpad-speed = 100

[options]
i444 = ''
collapse_toolbar = 'Y'
custom-fps = '30'
swap-left-right-mouse = ''
touch-mode = ''
zoom-cursor = ''
remote-menubar-drag-x = '0.5005382131324004'
codec-preference = 'auto'

[ui_flutter]
wm_RemoteDesktop = '{"width":1300.0,"height":740.0,"offsetWidth":320.0,"offsetHeight":171.0,"isMaximized":true,"isFullscreen":false}'

[info]
username = 'slova'
hostname = 'slova-latitude3420'
platform = 'Linux'

[transfer]
write_jobs = []
read_jobs = []
