remote_id = '56196847'
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
remote-menubar-drag-right = '1.0'
remote-menubar-drag-left = '0.0'

[ui_flutter]
wm_RemoteDesktop = '{"width":1920.0,"height":1003.0,"offsetWidth":0.0,"offsetHeight":27.0,"isMaximized":false,"isFullscreen":false}'
wm_Main = '{"width":796.0,"height":578.0,"offsetWidth":560.0,"offsetHeight":253.0,"isMaximized":true,"isFullscreen":false}'
peer-sorting = 'Remote ID'
