enc_id = '009spnVBIYdebDVysjma1i9gkjwTYMYQg7ew=='
password = ''
salt = '55mj7w'
key_pair = [
    [
    185,
    162,
    39,
    104,
    132,
    217,
    200,
    106,
    110,
    249,
    51,
    124,
    218,
    255,
    192,
    206,
    245,
    11,
    96,
    144,
    178,
    195,
    140,
    145,
    223,
    46,
    17,
    200,
    153,
    140,
    198,
    126,
    224,
    231,
    238,
    107,
    194,
    6,
    160,
    189,
    218,
    139,
    239,
    172,
    73,
    250,
    190,
    64,
    100,
    91,
    12,
    155,
    84,
    64,
    82,
    184,
    212,
    141,
    73,
    123,
    112,
    170,
    123,
    37,
],
    [
    224,
    231,
    238,
    107,
    194,
    6,
    160,
    189,
    218,
    139,
    239,
    172,
    73,
    250,
    190,
    64,
    100,
    91,
    12,
    155,
    84,
    64,
    82,
    184,
    212,
    141,
    73,
    123,
    112,
    170,
    123,
    37,
],
]
key_confirmed = true

[keys_confirmed]
rs-ny = true
